version: '2'
services:

  mongo:
    container_name: 'rsu_mongo'
    image: 'mongo'
    networks:
      rsu_net:
        ipv4_address: 172.15.123.11

  redis:
    container_name: 'rsu_redis'
    image: 'redis'
    networks:
      rsu_net:
        ipv4_address: 172.15.123.12

networks:
  rsu_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.123.0/24
